name: Docker build on push or pull-request

on:
  push:
    branches:
      - main
      - develop

    # Igore these files
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'

  # Run tests for any PRs.
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:
  
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: "nextcloud"

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    if: contains('pull_request', github.event_name)
        || (github.event_name == 'push' && github.ref != 'refs/heads/main')
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  multi:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/develop')
        || (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main')
        || github.event_name == 'schedule'

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Get version information
        id: image_information
        run: |
          IMAGE_ID=${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest-dev

          echo ::set-output name=IMAGE_ID::${IMAGE_ID}
          echo ::set-output name=IMAGE_REF::${VERSION}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.image_information.outputs.IMAGE_ID }}:${{ steps.image_information.outputs.IMAGE_REF }}
            ghcr.io/${{ steps.image_information.outputs.IMAGE_ID }}:${{ steps.image_information.outputs.IMAGE_REF }}
